# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcloudFzf < Formula
  desc ""
  homepage ""
  version "1.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgatewood/gcloud-fzf/releases/download/v1.0.6/gcloud-fzf_Darwin_x86_64.tar.gz"
      sha256 "d0438ed72ce4de1b07a4af6f9ce4649c95cd3db1e126965d5e444fbba4a70ba7"

      def install
        bin.install "gcloud-fzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgatewood/gcloud-fzf/releases/download/v1.0.6/gcloud-fzf_Darwin_arm64.tar.gz"
      sha256 "af09ddb5734e477b8207466557cd5967d24306646d4c7149694d97443a60766f"

      def install
        bin.install "gcloud-fzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgatewood/gcloud-fzf/releases/download/v1.0.6/gcloud-fzf_Linux_x86_64.tar.gz"
        sha256 "eac477df1c921bbdc70aa4f1d0e598932ba5f0a52877231c80b431d352ff4827"

        def install
          bin.install "gcloud-fzf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgatewood/gcloud-fzf/releases/download/v1.0.6/gcloud-fzf_Linux_arm64.tar.gz"
        sha256 "bb467935f6f063cce7e056bd43462ce2be25f6b96d007cf5b0efa3f45c8490c5"

        def install
          bin.install "gcloud-fzf"
        end
      end
    end
  end

  test do
    system "#{bin} --version"
  end
end
