# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcloudFzf < Formula
  desc ""
  homepage ""
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgatewood/gcloud-fzf/releases/download/v1.0.3/gcloud-fzf_Darwin_x86_64.tar.gz"
      sha256 "123a16deec73b482cd9ddf72cb2afd470fae6f53cb86ef223f1bdb532e89fe68"

      def install
        bin.install "gcloud-fzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgatewood/gcloud-fzf/releases/download/v1.0.3/gcloud-fzf_Darwin_arm64.tar.gz"
      sha256 "4ee5572a0468b451264f5753dadfce926aef60d7d86061b0c9023eb248d96e47"

      def install
        bin.install "gcloud-fzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgatewood/gcloud-fzf/releases/download/v1.0.3/gcloud-fzf_Linux_x86_64.tar.gz"
        sha256 "49500ec58cb9caabcf2cf000b9524d54fad8c57f51bafb808413943f10ec2c21"

        def install
          bin.install "gcloud-fzf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgatewood/gcloud-fzf/releases/download/v1.0.3/gcloud-fzf_Linux_arm64.tar.gz"
        sha256 "e6a1be8735095350335fcad13d5afee8841bf7f40f54c15f4e4a76f9d17313a0"

        def install
          bin.install "gcloud-fzf"
        end
      end
    end
  end

  test do
    system "#{bin} --version"
  end
end
